[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "MAPS"
version = "0.0.1"
description = "MAGIA mesh scheduler"
requires-python = ">=3.10"
dependencies = [
  "numpy==2.1.2",
  "onnx==1.20.1",
]

[project.scripts]
maps = "MAPS.cli:main"

[project.optional-dependencies]
dev = [
  "debugpy==1.8.20",
  "netron==8.9.6",
  "pynvim==0.6.0",
  "pytest==9.0.2",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["MAPS*"]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
