"""Concrete chip descriptions."""

from .magia import (
    MAGIA_L1_DATA_BYTES,
    MAGIA_L1_RESERVED_BYTES,
    MAGIA_L1_SIZE_BYTES,
    MAGIA_L1_STACK_BYTES,
    MAGIA_L1_USABLE_BYTES,
    MAGIA_L2_SIZE_BYTES,
    MAGIA_MESH_HEIGHT,
    MAGIA_MESH_WIDTH,
    magia_mesh,
)
from .n300d import (
    N300D_L1_RESERVED_BYTES,
    N300D_L1_SIZE_BYTES,
    N300D_L1_STACK_BYTES,
    N300D_L1_USABLE_BYTES,
    N300D_L2_SIZE_BYTES,
    N300D_MESH_HEIGHT,
    N300D_MESH_WIDTH,
    wormhole_n300d_mesh,
)

__all__ = [
    "MAGIA_L1_DATA_BYTES",
    "MAGIA_L1_RESERVED_BYTES",
    "MAGIA_L1_SIZE_BYTES",
    "MAGIA_L1_STACK_BYTES",
    "MAGIA_L1_USABLE_BYTES",
    "MAGIA_L2_SIZE_BYTES",
    "MAGIA_MESH_HEIGHT",
    "MAGIA_MESH_WIDTH",
    "magia_mesh",
    "N300D_L1_RESERVED_BYTES",
    "N300D_L1_SIZE_BYTES",
    "N300D_L1_STACK_BYTES",
    "N300D_L1_USABLE_BYTES",
    "N300D_L2_SIZE_BYTES",
    "N300D_MESH_HEIGHT",
    "N300D_MESH_WIDTH",
    "wormhole_n300d_mesh",
]
