"""Reusable tile-local device definitions."""

from .generic import GENERIC_SCALAR_DEVICE, IDMA_READ_DEVICE, IDMA_WRITE_DEVICE, SCALAR_DEVICE
from .tenstorrent import TENSIX_MATRIX_DEVICE, TENSIX_SCALAR_DEVICE, TENSIX_VECTOR_DEVICE

__all__ = [
    "GENERIC_SCALAR_DEVICE",
    "IDMA_READ_DEVICE",
    "IDMA_WRITE_DEVICE",
    "SCALAR_DEVICE",
    "TENSIX_MATRIX_DEVICE",
    "TENSIX_SCALAR_DEVICE",
    "TENSIX_VECTOR_DEVICE",
]
