"""Reusable tile-local device definitions."""

from .generic import GENERIC_CORE_DEVICE, IDMA_READ_DEVICE, IDMA_WRITE_DEVICE, SCALAR_CORE_DEVICE
from .tenstorrent import TENSIX_MATRIX_DEVICE, TENSIX_SCALAR_DEVICE

__all__ = [
    "GENERIC_CORE_DEVICE",
    "IDMA_READ_DEVICE",
    "IDMA_WRITE_DEVICE",
    "SCALAR_CORE_DEVICE",
    "TENSIX_MATRIX_DEVICE",
    "TENSIX_SCALAR_DEVICE",
]
